// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5qVAZWNooWrFxe0Aig0Jg6uStDVoeJhQ',
    appId: '1:92702362674:web:a3dcaafb4110bac514802b',
    messagingSenderId: '92702362674',
    projectId: 'chat-app-47c1a',
    authDomain: 'chat-app-47c1a.firebaseapp.com',
    storageBucket: 'chat-app-47c1a.appspot.com',
    measurementId: 'G-ZDFBWGJMSB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdXv4-EP9wTJWxa4pE6vPf_HOAR5N1LA8',
    appId: '1:92702362674:android:aba0153c938a5e7314802b',
    messagingSenderId: '92702362674',
    projectId: 'chat-app-47c1a',
    storageBucket: 'chat-app-47c1a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU6uujXxIwezDE3vXzqe_DJr0wgh_sb5w',
    appId: '1:92702362674:ios:81f914c92bab007c14802b',
    messagingSenderId: '92702362674',
    projectId: 'chat-app-47c1a',
    storageBucket: 'chat-app-47c1a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU6uujXxIwezDE3vXzqe_DJr0wgh_sb5w',
    appId: '1:92702362674:ios:81f914c92bab007c14802b',
    messagingSenderId: '92702362674',
    projectId: 'chat-app-47c1a',
    storageBucket: 'chat-app-47c1a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5qVAZWNooWrFxe0Aig0Jg6uStDVoeJhQ',
    appId: '1:92702362674:web:cb11e99d7af51b7b14802b',
    messagingSenderId: '92702362674',
    projectId: 'chat-app-47c1a',
    authDomain: 'chat-app-47c1a.firebaseapp.com',
    storageBucket: 'chat-app-47c1a.appspot.com',
    measurementId: 'G-HNE90KWRSB',
  );

}